
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash

    - name: Make zip file #1
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials #2
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
        aws-region: ap-northeast-2

    - name: Upload to S3 #3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://reactionGame/$GITHUB_SHA.zip

    - name: Code Deploy #4
      run: aws deploy create-deployment --application-name reactionGame
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name Green
        --s3-location bucket=reactionGame,bundleType=zip,key=$GITHUB_SHA.zip
