
name: deploy


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Make zip file 
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
      
    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: abhilash1in/aws-secrets-manager-action@v1.1.0
      with:
        aws-access-key-id: $ {{secrets.AWS_ACCESS_KEY_ID}} 
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION }} 
        secrets: |
          /secret/reactionGame
        parse-json: true
        
    - name: Upload to S3 #3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://reactiongame/$GITHUB_SHA.zip
        
      
    - name: Code Deploy #4
      run: aws deploy create-deployment --application-name reactionGame
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name Green
        --s3-location bucket=reactionGame,bundleType=zip,key=$GITHUB_SHA.zip


